---
- hosts: all
  roles:
    - all

- hosts: vms
  roles:
    - vms

- hosts: router
  roles:
    - router

- hosts: gitea
  roles:
    - auto-upgrades
    - gitea

- hosts: nextcloud
  roles:
    - auto-upgrades
    - nextcloud

- hosts: harbor
  roles:
    - auto-upgrades
    - docker
    - harbor

- hosts: desktop
  roles:
    - desktop

- hosts: k8s
  roles:
    - auto-upgrades
    - docker
    - k8s-all

- hosts: k8s-control-plane
  roles:
    - k8s-control-plane

- hosts: k8s_nodes
  roles:
    - k8s-nodes

- hosts: octopi
  roles:
    - octopi
