---
- hosts: all
  roles:
    - all

- hosts: vms
  roles:
    - vms

- hosts: router
  roles:
    - router

- hosts: gitea
  roles:
    - auto_upgrades
    - gitea

- hosts: nextcloud
  roles:
    - auto_upgrades
    - nextcloud
