---
- hosts: all
  roles:
    - all

- hosts: vms
  roles:
    - vms

- hosts: router
  roles:
    - router

- hosts: gitea
  roles:
    - auto-upgrades
    - gitea

- hosts: nextcloud
  roles:
    - auto-upgrades
    - nextcloud

- hosts: harbor
  roles:
    - auto-upgrades
    - docker
    - harbor

- hosts: k8s
  roles:
    - auto-upgrades
    - docker
    - k8s-all

- hosts: k8s-master
  roles:
    - k8s-master

- hosts: k8s_nodes
  roles:
    - k8s-nodes
