---
- when: |
    (ansible_distribution != 'Debian' or ansible_distribution_version != '10') and
    (ansible_distribution != 'Ubuntu' or ansible_distribution_version != '20.04')
  name: check platform
  fail:
    msg: This role requires Debian 10 or Ubuntu 20.04

- name: install open-vm-tools
  become: true
  apt:
    name: open-vm-tools

- name: enable and start open-vm-tools service
  become: true
  systemd:
    enabled: true
    state: started
    name: open-vm-tools
